language: node_js
node_js:
- '0.10'
notifications:
  slack:
    secure: qJA648I8BhciOg3oJ3rcFxAQRs27rXlLWn7OnApxRg3PNDD3YixEcbUXHLoj+wglRsPxVukR2CNxfy8as0aDmJFVMCIkdgVOOrEnZxsDwcdat7n4JaahEFFFzwXIW541/QAWCWlQB/lyzsC9Jmf38gdzId+ChPVDKM+/ccDCaE/Yi/kVLc8DQ4zrObY7gV5K5gZoBc4jlGHGFLpg8GurPRVgFDp59TGe6CZWSY1ps6bPA9EOYiWwJJN0mSf9nM6ulyRsnd90ReGc2mhdm9OlIyjXfPcx5mPNozPxeAG00iRIAR32qXCajYcGMFzqIFnTmYWZHg6cgebQdo29kEbfbjIa61P1+dVeMnmlKRPviYWk4xRXgB2t8rlHSipfQOYkLhstY5KE36pd25YCXSXZbI49oUXTpHeS+wgeq1GOnXfGIiSWCs3iLA4LHPR2UgW1JgpYIOq2AEb3zTGpogOJCf3wO2593E2ZMnOK1bzoSYiroeErU0wd8YpW5QzFMv6GdKeoyLu86E8WBefuV3p8XTHj9b7LtReJsWJp+x7f/KluNtVLFOWZesR0UcT7EeDdR9SQD0ShjBKjaz8Tm2gXFXAEMKV+/AP6gAR21SbkCquNf2eE5MLBh16cM3UHgrQbcarHrmXJbyl8jP4OX11XXO2nG9mLz9bx6JttaLuMx/o=
